name: Generate Pac-Man Graph

on:
  # Chạy tự động mỗi 24h
  schedule:
    - cron: "0 0 * * *" 
  # Cho phép chạy thủ công
  workflow_dispatch:
  # Chạy khi có push vào branch main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman-graph
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate Pac-Man Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
